shellcheck

diff --git a/displayctl b/displayctl
--- a/displayctl
+++ b/displayctl
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-set -eo pipefail
+set -e
 
 # get the primary display
 PRIMARY=$(xrandr | grep "^eDP-[0-9] connected" | awk '{print $1}')
@@ -13,11 +13,11 @@ fi
 EXTERNAL=$(xrandr | grep -E "^(DP|HDMI)-[0-9] connected" | head -n1 | awk '{print $1}')
 
 function usage {
-	echo "$(basename $0)"
+	echo "$(basename "$0") 0.1.0"
 	echo "Control internal and external display output"
 	echo ""
 	echo "USAGE:"
-	echo "    $(basename $0) [OPTION]"
+	echo "    $(basename "$0") [OPTION]"
 	echo ""
 	echo "OPTIONS:"
 	echo "    dual       turn both primary and extarnal displays on"
@@ -26,20 +26,50 @@ function usage {
 	exit 1
 }
 
+function dual {
+	# if no external display, fail
+	if [ -z "${EXTERNAL}" ]; then
+		echo "could not determine external display"
+		exit 1
+	fi
+
+	xrandr --output "${PRIMARY}" --auto --left-of "${EXTERNAL}" --output "${EXTERNAL}" --auto --primary
+	i3-msg restart
+}
+
+function primary {
+	# if no external display, set primary only
+	if [ -z "${EXTERNAL}" ]; then
+		xrandr --output "${PRIMARY}" --auto --primary
+	else
+		xrandr --output "${PRIMARY}" --auto --primary --output "${EXTERNAL}" --auto --off
+	fi
+
+	i3-msg restart
+}
+
+function external {
+	# if no external display, fail
+	if [ -z "${EXTERNAL}" ]; then
+		echo "could not determine external display"
+		exit 1
+	fi
+
+	xrandr --output "${PRIMARY}" --off --output "${EXTERNAL}" --auto --primary
+	i3-msg restart
+}
+
 case "$1" in
 	dual)
-		xrandr --output ${PRIMARY} --auto --left-of ${EXTERNAL} --output ${EXTERNAL} --auto --primary
+		dual
 		;;
 	primary)
-		xrandr --output ${PRIMARY} --auto --primary --output ${EXTERNAL} --auto --off
+		primary
 		;;
 	external)
-		xrandr --output ${PRIMARY} --off --output ${EXTERNAL} --auto --primary
+		external
 		;;
 	*)
 		usage
 		;;
 esac
-
-# restart i3 on display update
-i3-msg restart
